### ISSUE TITLE
honeycomb layout citation

### ISSUE THREAD

**Issue by egonw** [cdk/cdk-paper-3#29]
"systems much better, using a honeycomb layout approach~\cite{FIXME}, % FIXME"

**Comment by johnmay** [comment]
? It doesn't do that at all.

**Comment by egonw** [comment]
:) Just think of that line to have the intention to explain how you now lay out larger ring systems... they used to asymptotically create round rings, and now they don't... I thought I had remembered you used some published approach, but clearly misremembered that :)

**Comment by johnmay** [comment]
Sorry still meant to do this... very busy time (got married two days ago).
