### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by johnmay** [cdk/cdk-paper-3#32]
http://blogs.sciencemag.org/pipeline/archives/2016/08/31/predicting-new-reactions

**Comment by egonw** [comment]
@johnmay how do you want to see this cited? There are many peer-reviewed papers where the fingerprint is used: http://www.citeulike.org/user/egonw/tag/cdk--usespackage--fingerprint

**Comment by johnmay** [comment]
True but a lot of those are other software packages.. just a nice paper.
It's not actually been published yet just one to keep an eye on.

**Comment by johnmay** [comment]
What I mean there is.. citations about applications of fingerprints to
solve a problem vs 'you can calculate fingerprints, we use CDK'.

**Comment by mrwns** [comment]
@johnmay @egonw I am the first author of the paper. 
In the project, we used CDK for (basically) all cheminformatics steps, from parsing to the core program logic. More specifically, we used CDK to 

a) parse RD files (we implemented an RDF parser for that)
b) canonicalize smiles
c) determine which atoms get changed in reactions
d) compute reaction fingerprints (we implemented an "IReactionFingerprinter" that wraps any IFingerprinter able to generate ICountFingerprints to produce reaction fingerprints like those from Schneider et al.)
e) calculate similarity 
f)  create the product structures for the predicted reactions
g) display structures and reactions in the UI with cdk-depict

I would say without CDK we would not have been able to do the project.

If there is interest in including some of the features we implemented to CDK, I would be happy to contribute!

**Comment by egonw** [comment]
@mrwns, yes, the IReactionFingerprinter would be really interesting. The RD file readers as a special kind... we actually have(d?) one in the CDK for the RD files used in the MaCIE database... but these files are indeed non-standard, i.e. vary from one database to another...
