### ISSUE TITLE
Github replace SourceForge - Alive

### ISSUE THREAD

**Issue by miquelrojascherto** [cdk/cdk-paper-3#40]
In section Git, branching, and patches is informed that Github has replaced Sourcforge. But I still see in the  sourforge page (https://sourceforge.net/projects/cdk/) alive. Should it not be commented anything on that?

**Comment by tomas-pluskal** [comment]
Just a comment on this: wouldn't it be better to redirect the SF page to https://github.com/cdk/cdk ? The current SF page does not seem to contain anything really useful.

**Comment by egonw** [comment]
The mailing lists are still there. Google Groups can be a solution, but this migration has not been done yet.
