### ISSUE TITLE
More performance benchmarks?

### ISSUE THREAD

**Issue by rajarshi** [cdk/cdk-paper-3#50]
It would be nice to show performance benchmarks comparing the latest release (or current master) with a 1.4 or older release - to make it clear that performance has significantly improved. Features to benchmark could include
- type perception (speed and coverage)
- SMILES parsing/generation
- Fingerprinting (depending on fingerprint type this will include aromaticity, SMARTS performance)

The downside is that this is a good chunk of work, though maybe the test cases could be reused for this purpose

**Comment by egonw** [comment]
For atom typing, we did not really have that separate before, so nothing really to compare too.

**Comment by egonw** [comment]
Reviewer #2 asks for this too:

    Performance improvements are prominently mentioned in the abstract, however there isn't really a 
    proper systematic evaluation of performance against previous CDK versions and other toolkits. I 
    appreciate that this can be tricky to do in some cases, but at the very least I think the existing limited 
    benchmarks for formula generation and SMARTS matching could be expanded on. At present, they are 
    presented without much discussion - what were the performance bottlenecks? How exactly were they 
    overcome?

How about comparing the current CDK for two or three Chemistry Toolkit Rosetta tasks?

**Comment by johnmay** [comment]
Okay will do.

**Comment by johnmay** [comment]
Done

**Comment by egonw** [comment]
Time to close this issue?
