### ISSUE TITLE
Figures don't use figure environment

### ISSUE THREAD

**Issue by rajarshi** [cdk/cdk-paper-3#53]
Is this a JCheminf requirement? By not using figure env's we can't properly reference figure labels

**Comment by egonw** [comment]
No, this BMC template indeed does not use them. Still, I tried it, but even then references don't work... so, the manuscript uses \ref{} but we still hardcode the number... :(

**Comment by egonw** [comment]
OK, you clearly got it working... weird, because I'm pretty sure I tried...

**Comment by egonw** [comment]
But, there are now some numbering inconsistencies that need fixing... (no worries...)

**Comment by rajarshi** [comment]
Yes - because I haven't figured out how to get the verbatim block into an environment that can be labeled
