### ISSUE TITLE
make clear pointer on the SF project page about the new "front page"

### ISSUE THREAD

**Issue by egonw** [cdk/cdk-paper-3#69]

**Comment by johnmay** [comment]
We can just redirect?

**Comment by rajarshi** [comment]
I'd go for a redirect

**Comment by johnmay** [comment]
Definitely read it's possible but can't find the link on how to do it now

**Comment by tomas-pluskal** [comment]
It's easy to do with JavaScript, isn't it?
````
window.location.replace('https://cdk.github.io');
````

**Comment by steinbeck** [comment]
Guys, the new web page looks fantastic!

Cheers, 

Chris

— 
Prof. Dr. Christoph Steinbeck
Friedrich-Schiller-University Jena, Germany
Phone Secretariat: +49-3641-948171
http://orcid.org/0000-0001-6966-0814

What is man but that lofty spirit - that sense of enterprise.
... Kirk, "I, Mudd," stardate 4513.3..

**Comment by johnmay** [comment]
@tomas-pluskal or .htaccess but that's not the difficult bit. It definitely possible to do it from (cdk.sourforge.net - which isn't actually used) but not sure from sourceforge.net/projects/cdk...

**Comment by johnmay** [comment]
Should be clear now: https://sourceforge.net/projects/cdk/

Marked as moved... of course we still use the mailing lists..

**Comment by johnmay** [comment]
Out of interest Egon, are you manually pushing the github to SF?

**Comment by egonw** [comment]
1. I'm backing up stuff from SF...
2. we still haven't finalized defining a replacement for the mailing lists

Yes, regarding git, I'm doing that whenever I pull changes into my local checkout:

    git fetch origin; git rebase origin/master; git push sf; git push github

(the second push is to my GH copy of the repos, for my development branches, tho not so many nowadays...)

**Comment by egonw** [comment]
http://cdk.sf.net/ still redirects to an old page, i.e. https://sourceforge.net/apps/mediawiki/cdk/index.php?title=Main_Page

**Comment by johnmay** [comment]
Have just logged into the sftp, removed the index.html and replaced with the index.php as suggested by their help section. Might take a while to take effect.

**Comment by egonw** [comment]
Oh, excellent... it's been too long for me... I did not even remember that.

**Comment by egonw** [comment]
(PS, I don't want to delete the SF project, so that it cannot be taken over by someone else...)

**Comment by johnmay** [comment]
No I agree.. okay should be live now watch out for browser caching.

**Comment by johnmay** [comment]
Here's how you can grab the site if you're interested:

```
scp -r jwmay@web.sourceforge.net:/home/project-web/cdk/htdocs htdocs
```

obviously with your username
