### ISSUE TITLE
Code Examples

### ISSUE THREAD

**Issue by johnmay** [cdk/cdk-paper-3#76]
Maybe we should render the code examples to PDFs. I'm not sure I trust the formatting to get this looking nice - the verbatim doesn't look great at the moment. The problem is these would then be inline images which would need to be labelled?

**Comment by rajarshi** [comment]
Yes, that'd preserve formatting, but will it allow copy/paste?

**Comment by egonw** [comment]
I rather have text... but since SpringerOpen has not rolled out improvements in this area yet (which will allow c/p-ing; we have a task set out for this internally), not sure we should... so, yes, please go for PDF.

**Comment by egonw** [comment]
I will make sure to also put it as separate file in the SuppInfo, then it will be a file on Figshare and that should be copy/pastable...

**Comment by johnmay** [comment]
Will they need to go at the end of the document? Note sure how inline pictures work with the journal style? Cheers

**Comment by johnmay** [comment]
This is proving more difficult then I thought. Might idea was to render via HTML using prettyprint and then convert to PDF, but the conversion tools I found generate an A4.

**Comment by johnmay** [comment]
Hmm... what I could do is generate n pages with all the code examples on it and then crop via latex. That will be very brittle though... any ideas?

**Comment by johnmay** [comment]
Hmm.. brittle but actually feasible

**Comment by johnmay** [comment]
Note for me... maybe use pygments https://gist.github.com/peterc/1861451

**Comment by johnmay** [comment]
Will leave as it is.
