### ISSUE TITLE
Make a list with all files to add as Supp Info

### ISSUE THREAD

**Issue by egonw** [cdk/cdk-paper-3#77]
I'm going to need this list during resubmission, to ensure I don't forget files... and I don't want to put it in a zip file, and try to take full advantage of the new Figshare functionality...

**Comment by tomas-pluskal** [comment]
Do you want to include the code that was used to generate the benchmarks (e.g., https://github.com/cdk/cdk-paper-3/tree/master/formula_generator_evaluation)?

**Comment by johnmay** [comment]
The entire `benchmark/` directory. Someone should test it works though from the https://github.com/cdk/cdk-paper-3/blob/master/benchmark/README.md

**Comment by johnmay** [comment]
Maybe we zip up the benchmark... so as not to add all the files
